### ISSUE TITLE
Status of link in input3

### ISSUE THREAD

**Issue by ehsan-shafiee** [USEPA/Water-Distribution-Network-Model#35]
If the name of a link is more than MAXID (=31), the link cannot be found in hashtable at line 1276 in input3.c file. The line reads if ((j = findlink(net, parser->Tok[0])) == 0) return setError(parser, 0, 204);

The case was tested holds a pump with ("MAIREHAU_PUMP_STAND_BY_US.MAIREHAU_PUMP_STAND_BY_DS.1") name. The file is runnable with EPANET 2.0 but, it throws error 204 in EPANET 2.2.

One or two ways can be proposed to fix this issue. Throwing errors when the length of names exceeds 31 characters can be a good solution. I think this is a good solution, because if the 31 first characters of two links are the same, a wrong index may be found in the hashtable.

**Comment by michaeltryby** [comment]
I agree that an error should be thrown when an ID exceeds its fixed length.

**Comment by ehsan-shafiee** [comment]
Okay, thanks. I will make changes and submit a pull-request.
