### ISSUE TITLE
Update license file from CC0 to MIT

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/Water-Distribution-Network-Model#6]
@terrahaxton I merged OWA's code into our repository so the license is no longer CC0. In fact it is now MIT. As per the Contributors guidelines, since we have incorporated their code, we must now honor their license. Make sense? 

Also target your PRs to the "develop" branch going forward.

**Comment by rjanke20** [comment]
Why isn't it possible to retain multiple open source licenses?  That is, main code is CC0 and additions from the community could be MIT or BSD?

**Comment by michaeltryby** [comment]
@rjanke20 Good question. While it is possible using tools like git in practice it is impractical to determine which code belongs under which license. The common practice when merging code with compatible licenses is that the most restrictive license takes precedence over the less restrictive licenses. Basically, MIT only requires downstream users to display the license which is more restrictive than CC0 which requires the user to do nothing. 

 It is possible that in the future someone may wish to contribute under a more restrictive or incompatible license. In that case, we may chose to reject the contribution. 

The EPA merged OWA's code so we are now required to comply with the terms of their license. That's how OS licenses work. To comply with their license our repository now needs to display an MIT license. 

This shouldn't be a problem. We are allowed to hold the copyrighted work of other parties.

**Comment by michaeltryby** [comment]
Repository has been updated to display MIT License. Closing issue.
