### ISSUE TITLE
Perform QA on v2.2.0 beta release

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/Water-Distribution-Network-Model#9]
- [x] Refactor testing scripts for private testing
- [x] Get private tests running and under source code control
- [x] Generate benchmark using EPANET v2.0.12 for private test suite
- [x] Generate benchmark for SUT release candidate 
- [x] Investigate any differences

**Comment by fengshang1972** [comment]
Michael

Do you have a step by step instruction of doing the "private test" and evaluating against master benchmark? It seems quite a complicated process to me. Some documentations will certainly help.

**Comment by michaeltryby** [comment]
@fengshang1972 Unfortunately, I haven't gotten the private tests setup yet let alone documented. I just got the installer working this morning, so I can jump on it now.
